---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r results="hold"}
library(petro.One)
my_url <- make_search_url(query = "technical potential", 
                           how = "all")
get_papers_count(my_url)
# [1] 132
df <- read_multidoc(my_url)
df
```


## How many papers with "technical" and "potential"

```{r}
df$title <- tolower(df$title_data)

# df[grep("technical potential", df$title), c("title_data", "paper_id")]
```




## What are the most common 1-words

```{r}
library(tm)

tf1 <- term_frequency(df)
tf1
```



## What are the most common 2-word keywords

```{r}
library(RWeka)
term_frequency_n_grams <- function (df, gram.min = 2, gram.max = 2) 
{
    vdocs <- VCorpus(VectorSource(df$title_data))
    # this fixes the function in petro.One for international characters
    # See https://stackoverflow.com/questions/9637278/r-tm-package-invalid-input-in-utf8towcs
    vdocs <- tm_map(vdocs, content_transformer(function(x) iconv(enc2utf8(x), 
                                                                 sub = "byte")))
    vdocs <- tm_map(vdocs, content_transformer(tolower))
    vdocs <- tm_map(vdocs, removeWords, stopwords("english"))
    vdocs <- tm_map(vdocs, removeWords, custom_stopwords)
    vdocs <- tm_map(vdocs, stripWhitespace)
    vdocs <- tm_map(vdocs, removePunctuation)
    tdm <- TermDocumentMatrix(vdocs)
    tdm.matrix <- as.matrix(tdm)
    tdm.rs <- sort(rowSums(tdm.matrix), decreasing = TRUE)
    tdm.df <- data.frame(word = names(tdm.rs), freq = as.integer(tdm.rs), 
        stringsAsFactors = FALSE)
    options(mc.cores = 1)
    twogramTokenizer <- function(x) {
        NGramTokenizer(x, Weka_control(min = gram.min, max = gram.max))
    }
    tdm2 <- TermDocumentMatrix(vdocs, control = list(tokenize = twogramTokenizer))
    tdm2.matrix <- as.matrix(tdm2)
    tdm2.rs <- sort(rowSums(tdm2.matrix), decreasing = TRUE)
    tdm2.df <- data.frame(word = names(tdm2.rs), freq = tdm2.rs, 
        stringsAsFactors = FALSE)
    tibble::as.tibble(tdm2.df)
}

```



```{r}
tf2 <- term_frequency_n_grams(df, gram.min = 2, gram.max = 2)
tf2
```



```{r}
pattern <- "oil recovery"
df$title <- tolower(df$title_data)
df[grep(pattern, df$title), c("title_data", "paper_id")]
```

## Find `technical potential` in "malaysia operations"

```{r}
pattern <- "malaysia operations"
df$title <- tolower(df$title_data)
df[grep(pattern, df$title), c("title_data", "paper_id")]
```


```{r}
files <- list.files(pattern = ".pdf$")
files
```

```{r}
Rpdf <- readPDF(control = list(text = "-layout"))
```


```{r}
theFile <- "gupta2017.pdf"
gupta2017 <- Corpus(URISource(theFile), 
                   readerControl = list(reader = Rpdf))
inspect(gupta2017)
```


```{r}
# one-word terms in gupta2017 paper
gupta2017.tdm <- TermDocumentMatrix(gupta2017, 
                                    control = list(removePunctuation = TRUE, 
                                                   stopwords = TRUE,
                                                   tolower = TRUE,
                                                   removeNumbers = TRUE
                                                   #stemming = TRUE
                                                   ))
inspect(gupta2017.tdm)
```

```{r}
findFreqTerms(gupta2017.tdm, lowfreq = 50, highfreq = Inf)
```

# Term freqency analysis for the first paper

```{r}
# frequency analysis of gupta2017
theFile <- "gupta2017.pdf"
paper_corpus <- Corpus(URISource(theFile), 
                   readerControl = list(reader = Rpdf))

# inspect(paper_corpus)

# one-word terms in gupta2017 paper
paper.tdm <- TermDocumentMatrix(paper_corpus, 
                                    control = list(removePunctuation = TRUE, 
                                                   stopwords = TRUE,
                                                   tolower = TRUE,
                                                   removeNumbers = TRUE
                                                   #stemming = TRUE
                                                   ))
# inspect(paper.tdm)

findFreqTerms(paper.tdm, lowfreq = 50, highfreq = Inf)
findMostFreqTerms(paper.tdm)

tdm.matrix <- as.matrix(paper.tdm)
tdm.rs <- sort(rowSums(tdm.matrix), decreasing = TRUE)
tdm.df1 <- data.frame(word = names(tdm.rs), freq = tdm.rs, stringsAsFactors = FALSE)
tdm.df1

```


## Analizing the second paper `ruslan2014`

```{r}
# frequency analysis of ruslan2014
theFile <- "ruslan2014.pdf"
paper_corpus <- Corpus(URISource(theFile), 
                   readerControl = list(reader = Rpdf))

inspect(paper_corpus)

# one-word terms in gupta2017 paper
paper.tdm <- TermDocumentMatrix(paper_corpus, 
                                    control = list(removePunctuation = TRUE, 
                                                   stopwords = TRUE,
                                                   tolower = TRUE,
                                                   removeNumbers = TRUE
                                                   #stemming = TRUE
                                                   ))
inspect(paper.tdm)

findFreqTerms(paper.tdm, lowfreq = 50, highfreq = Inf)

tdm.matrix <- as.matrix(paper.tdm)
tdm.rs <- sort(rowSums(tdm.matrix), decreasing = TRUE)
tdm.df2 <- data.frame(word = names(tdm.rs), freq = tdm.rs, stringsAsFactors = FALSE)
tdm.df2

```

```{r}
tdm.matrix <- as.matrix(paper.tdm)
tdm.rs <- sort(rowSums(tdm.matrix), decreasing = TRUE)
tdm.df <- data.frame(word = names(tdm.rs), freq = tdm.rs, stringsAsFactors = FALSE)
tdm.df
```

```{r fig.asp=1.1}
library(ggplot2)
p1 <- ggplot(subset(tdm.df1, freq > 30), aes(x=word, y=freq)) + 
    geom_bar(stat = "identity") + 
    xlab("Terms") + ylab("Count") + 
    coord_flip()

p2 <- ggplot(subset(tdm.df2, freq > 30), aes(x=reorder(word, freq), y=freq)) + 
    geom_bar(stat = "identity") + 
    xlab("Terms") + ylab("Count") + 
    coord_flip()

require("gridExtra")
grid.arrange(arrangeGrob(p1, p2))
```


## Another interesting thing


```{r}
library(ggplot2)

p3 <- ggplot(subset(tf2, freq > 2), aes(x=word, y=freq)) + 
    geom_bar(stat = "identity") + 
    xlab("Terms") + ylab("Count") + 
    coord_flip()
p3
```



We acquire the two first papers and proceed to do some data mining on the PDF paper itself.

```{r}
dir(pattern = ".pdf")
```





```{r}
# opinions <- Corpus(URISource(files), 
#                    readerControl = list(reader = Rpdf))
# opinions.tdm <- TermDocumentMatrix(opinions, control = list(removePunctuation = TRUE,
#                                                          stopwords = TRUE,
#                                                          tolower = TRUE,
#                                                          stemming = TRUE,
#                                                          removeNumbers = TRUE,
#                                                          bounds = list(global = c(3, Inf)))) 
# inspect(opinions.tdm[1:2,]) 
```

